---
# Default variables for homebrew_dependencies
homebrew_packages:
  # base
  - git
  - wget
  - curl
  - vim
  - python3
  - node
  - npm
  
  # GitHub
  - gh
  
  # Xcode
  - xcodesorg/made/xcodes
  - aria2
  - graphviz
  
  # Swift
  - mint
