---
galaxy_info:
  author: marinofelipe
  description: Visual Studio Code installation and configuration
  min_ansible_version: 2.9
  platforms:
    - name: MacOSX
      versions:
        - all
dependencies: []
